name: Release older version to npm only.
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release to npm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Teszt
        run: |
          MSG=$(git log --format=%B -n 1 ${{ github.event.after }})
          ::set-env name=COMMIT_MESSAGE::${MSG}
  teszt:
    needs: release
    runs-on: ubuntu-latest
    name: ttteszt
    steps:
      - name: Tesztt
        run: echo %{{COMMIT_MESSAGE}}
