name: Release older version to npm only.
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release to npm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tesztt
        run: echo ${github.event.head_commit.message}
