name: Release older version to npm only.
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release to npm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Teszt
        run: |
          echo "action_state=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
