name: Release older version to npm only.
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release to npm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tesztt
        run: |
          MSG=$(git log --format=%B -n 1 ${{ github.event.after }})
          echo ${MSG}
