name: Release older version to npm only.
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release to npm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Teszt
        env:
          COMMIT_MESSAGE: ${{git log --format=%B -n 1 ${{ github.event.after }}}}
        run: echo "$COMMIT_MESSAGE"
