name: Release older version to npm only.
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release to npm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get commit message
        run: |
          echo "commmit_message=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.commmit_message }}" # This will output 'yellow'
  tryit:
    needs: release
    if: "startsWith(env.commmit_message, 'WIP: asd')"
    runs-on: ubuntu-latest
    name: Release to npm
    steps:
      - name: Get commit message
        run: |
          echo "Zsiiiiir"
