name: Release older version to npm only.
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release to npm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tesztt
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.head_commit.message) }}
        run: echo "$GITHUB_CONTEXT"
